---
# Create a group for every user and make that their primary group
users_create_per_user_group: true

# If we're not creating a per-user group, then this is the group all users
# belong to
users_group: users

# The default shell for a user if none is specified
users_default_shell: /bin/bash

# Create home dirs for new users? Set this to false if you manage home
# directories in some other way.
users_create_homedirs: true

# Lists of users to delete
users_deleted: []

# List of groups to create
groups_to_create: []

# location of authorized_keys
authorized_keys_file: ".ssh/authorized_keys"
